version: '3.7'

services:
  web:
    build: .
    environment:
      - CUSTOMIZATIONS_PATH=/temp
      - DEVENV_PATH=/app
    volumes:
      - yarn_cache:/yarn
      - node_modules_cache:/app/node_modules

volumes:
  yarn_cache:
  node_modules_cache:
